name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 3 * * *"

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-slim
    if: github.event_name != 'schedule'
    outputs:
      python-3_14: ${{ steps.filter.outputs.python-3_14 }}
      python-3_14-gdal: ${{ steps.filter.outputs.python-3_14-gdal }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            python-3_14:
              - 'python/3.14/**'
              - '.github/workflows/build-image.yml'
            python-3_14-gdal:
              - 'python/3.14-gdal/**'
              - '.github/workflows/build-image.yml'

  python-3_14:
    needs: changes
    if: always() && (github.event_name == 'schedule' || needs.changes.outputs.python-3_14 == 'true')
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      dockerfile_context: python/3.14
      image_name: python-3.14

  python-3_14-gdal:
    needs: [changes, python-3_14]
    if: always() && !failure() && !cancelled() && (github.event_name == 'schedule' || needs.changes.outputs.python-3_14 == 'true' || needs.changes.outputs.python-3_14-gdal == 'true')
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      dockerfile_context: python/3.14-gdal
      image_name: python-3.14-gdal
